export const DEFAULT_QUESTIONS_PER_LEVEL = 40;
export const DEFAULT_NUMBER_OF_LEVELS = 3;

export const MINIMUM_QUESTIONS_FOR_ANY_ANALYSIS = 10;
export const RECOMMENDED_QUESTIONS_FOR_BASIC_ANALYSIS = 20;
export const RECOMMENDED_QUESTIONS_FOR_ACCURATE_ANALYSIS = 40;
